### ISSUE TITLE
0.21.21 unable to run

### ISSUE THREAD

**Issue by luke-riu** [FlowCI/flow-agent-x#48]
Trying to run on Intel Mac, I get the output below. This is from both the tagged build and from my own `make` version
```bash
luke@Lukes-iMac Desktop % ./flow-agent-x-mac -u http://192.168.2.2:8080 -t 2ed6ce1c-afd1-401d-9029-6bb576db2b4c -m name=pyenv,dest=/ci/python,script=init.sh,image=flowci/pyenv:1.3,init=init-pyenv-volume.sh
INFO[2021-05-20T11:54:06+01:00] Staring flow.ci agent (v0.21.21)...          
INFO[2021-05-20T11:54:06+01:00] Agent is connected to server http://192.168.2.2:8080 
INFO[2021-05-20T11:54:06+01:00] --- [Server URL]: http://192.168.2.2:8080    
INFO[2021-05-20T11:54:06+01:00] --- [Token]: 2ed6ce1c-afd1-401d-9029-6bb576db2b4c 
INFO[2021-05-20T11:54:06+01:00] --- [Port]: 51725                            
INFO[2021-05-20T11:54:06+01:00] --- [Workspace]: /Users/luke/.flow.ci.agent 
INFO[2021-05-20T11:54:06+01:00] --- [Plugin Dir]: /Users/luke/.flow.ci.agent/.plugins 
INFO[2021-05-20T11:54:06+01:00] --- [Log Dir]: /Users/luke/.flow.ci.agent/.logs 
INFO[2021-05-20T11:54:06+01:00] --- [Volume Str]: name=pyenv,dest=/ci/python,script=init.sh,image=flowci/pyenv:1.3,init=init-pyenv-volume.sh 
INFO[2021-05-20T11:54:06+01:00] --- [Exit On Idle]: 0 (seconds)              
INFO[2021-05-20T11:54:06+01:00] [Agent Status] = Idle                        
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /cmds/:id                 --> reflect.methodValueCall (3 handlers)
[GIN-debug] POST   /cmds/                    --> reflect.methodValueCall (3 handlers)
[GIN-debug] GET    /health/                  --> reflect.methodValueCall (3 handlers)
DEBU[2021-05-20T11:54:16+01:00] ...                                          
panic: runtime error: index out of range [0] with length 0

goroutine 53 [running]:
github/flowci/flow-agent-x/config.(*Manager).FetchProfile(0xc0004cec80, 0xc00019a000)
	/ws/config/manager.go:105 +0x1ad
github/flowci/flow-agent-x/config.(*Manager).sendAgentProfile.func1(0xc0004cec80)
	/ws/config/manager.go:252 +0x44
created by github/flowci/flow-agent-x/config.(*Manager).sendAgentProfile
	/ws/config/manager.go:245 +0x3f
```

Does this look to be an issue with my agent or something else?
Thanks a lot
Luke

**Comment by luke-riu** [comment]
I'm not sure if this is related, but looking at the build agent, it is showing up as a Mac (apple logo) so I assume it's making contact. However, the IP of the agent is showing as `http:///172.1.0.1:49881`. I thought it odd that there was a triple slash there. I don't know if that is normal..

**Comment by luke-riu** [comment]
This appears to be the latest agent release (`0.21.21`) at fault as `0.21.05` runs ok on my Intel iMac

**Comment by gy2006** [comment]
it's a bug within the new release while CPU usage cannot be fetched.

I uploaded an image and binary with this fix, and also added an environment variable `FLOWCI_AGENT_PROFILE_ENABLED` that can disable agent profiling. if it doesn't work with your M1 Mac and not important, you can disable it by `FLOWCI_AGENT_PROFILE_ENABLED=false`
